apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-url-deploy
  labels:
    app: short-url
spec:
  replicas: 2
  selector:
    matchLabels:
      app: short-url
  template:
    metadata:
      labels:
        app: short-url
    spec:
      containers:
      - name: short-url
        image: josephshih13/short-url
        ports:
        - containerPort: 1323
        env:
        - name: REDIS_URL
          value: "redis-master:6379"
        imagePullPolicy: "Always"
---
apiVersion: v1
kind: Service
metadata:
  name: short-url-svc
spec:
  ports:
    - port: 1323
      targetPort: 1323
      protocol: TCP
  selector:
    app: short-url
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: short-url-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: short-url-svc
              servicePort: 1323
